In [2]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt

In [4]:
data = pd.read_csv("../data/housing_demo.csv")
np.set_printoptions(precision=2, suppress=True)

X = data.to_numpy()[:,:-1]
Y = data.to_numpy()[:,-1]

print("X : ",X)
print("Y : ",Y)

# dimention = x.size() * x[0].size()
rng = np.random.default_rng(seed=42)
beta_param = rng.random(size=(len(X[0]), len(X)))
print("BETA : ",beta_param)


X :  [[1659.01    2.  ]
 [1468.52    1.  ]
 [1704.31    5.  ]
 ...
 [1298.4     5.  ]
 [1658.73    4.  ]
 [1703.32    2.  ]]
Y :  [864521.86 722252.75 939413.7  ... 807821.52 825368.42 782359.54]
BETA :  [[0.77 0.44 0.86 ... 0.17 0.37 0.48]
 [0.72 0.71 0.2  ... 0.85 0.67 0.14]]


In [7]:
# impliment ridge regression 

L = 0.3;
I = np.eye((X.T @ X).shape[0])
B_RIDGE = np.linalg.inv(X.T @ X + L * I ) @ X.T * Y 
print(B_RIDGE)

[[  0.14   0.15  -0.07 ...  -0.12   0.     0.14]
 [-43.58 -56.15  70.32 ...  87.43  29.39 -42.28]]
