In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

np.float64(0.574442516811659)

In [45]:
data = pd.read_csv("./data/heart.csv").to_numpy()

# need 1 more col containing 1s so we can have a scaling factor beta_n
expected_output = data[:,-1]
scaling_col = np.ones((data.shape[0], 1))
data = data[:,:-1]
data = np.column_stack((data,scaling_col))


# geneate a parameter matrix 
# size = len(data[0])

rng = np.random.default_rng()
beta_param = rng.normal(0, 0.01, data.shape[1])

print(data)
print(data.shape)
print(beta_param)
print(beta_param.shape)

[[52.  1.  0. ...  2.  3.  1.]
 [53.  1.  0. ...  0.  3.  1.]
 [70.  1.  0. ...  0.  3.  1.]
 ...
 [47.  1.  0. ...  1.  2.  1.]
 [50.  0.  0. ...  0.  2.  1.]
 [54.  1.  0. ...  1.  3.  1.]]
(1025, 14)
[-0.00273202  0.01572554 -0.00237211 -0.01519031  0.00530503  0.01039524
  0.011849    0.00389219  0.0019965   0.00545228 -0.01354515  0.00126544
  0.00354702  0.00130323]
(14,)


In [ ]:
# predicted value 

val = sigmoid(data @ beta_param)
eps = 1e-15
p = np.clip(val, eps, 1 - eps)

# cross-entropy loss 

log_likelihood = np.sum(
    expected_output * np.log(p)
    + (1 - expected_output) * np.log(1 - p)
) / len(data)

gradient = 1/len(data) * ( data.T @ (p - expected_output) )
learning_rate = 0.01
beta_param -= learning_rate * gradient
epochs = 1025

for epoch in range(epochs):

    z = data @ beta_param

    val = sigmoid(z)

    gradient = data.T @ (val - expected_output) / len(expected_output)

    beta_param -= learning_rate * gradient


0.0
